//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMIC.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAIVETSANPHAM
    {
        public System.Guid MABV { get; set; }
        public Nullable<System.Guid> MASP { get; set; }
        public string TIEUDE { get; set; }
        public string NOIDUNG { get; set; }
        public Nullable<bool> ISPENDING { get; set; }
        public Nullable<bool> ISPUBLISH { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
