//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMIC.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BINHLUAN
    {
        public System.Guid MABL { get; set; }
        public Nullable<System.Guid> MANV { get; set; }
        public Nullable<System.Guid> MASP { get; set; }
        public string NOIDUNG { get; set; }
        public Nullable<System.DateTime> NGAYBINHLUAN { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
