//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMIC.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETKHUYENMAI
    {
        public int MALOAIKM { get; set; }
        public System.Guid MASP { get; set; }
        public Nullable<System.DateTime> NGAYBATDAUKM { get; set; }
        public Nullable<System.DateTime> NGAYKETTHUCKM { get; set; }
        public Nullable<int> PHANTRAM { get; set; }
    
        public virtual LOAIKHUYENMAI LOAIKHUYENMAI { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
