//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMIC.Models.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_HOABANFOOD_VER2Entities : DbContext
    {
        public DB_HOABANFOOD_VER2Entities()
            : base("name=DB_HOABANFOOD_VER2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ANHSANPHAM> ANHSANPHAMs { get; set; }
        public virtual DbSet<BAIVETSANPHAM> BAIVETSANPHAMs { get; set; }
        public virtual DbSet<BINHLUAN> BINHLUANs { get; set; }
        public virtual DbSet<CHITIETDATHANG> CHITIETDATHANGs { get; set; }
        public virtual DbSet<CHITIETKHUYENMAI> CHITIETKHUYENMAIs { get; set; }
        public virtual DbSet<DANHGIA> DANHGIAs { get; set; }
        public virtual DbSet<DANHMUCSANPHAM> DANHMUCSANPHAMs { get; set; }
        public virtual DbSet<DONDATHANG> DONDATHANGs { get; set; }
        public virtual DbSet<LOAIKHUYENMAI> LOAIKHUYENMAIs { get; set; }
        public virtual DbSet<LOAINHANVIEN> LOAINHANVIENs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<SANPHAM> SANPHAMs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<VIDEOSANPHAM> VIDEOSANPHAMs { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<SP_GET_ALL_ANH_Result> SP_GET_ALL_ANH()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_ALL_ANH_Result>("SP_GET_ALL_ANH");
        }
    
        public virtual ObjectResult<SP_GET_ALL_ANH_SP_BY_ID_Result> SP_GET_ALL_ANH_SP_BY_ID(string mASP)
        {
            var mASPParameter = mASP != null ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_ALL_ANH_SP_BY_ID_Result>("SP_GET_ALL_ANH_SP_BY_ID", mASPParameter);
        }
    
        public virtual ObjectResult<SP_GET_ALL_BAIVIET_Result> SP_GET_ALL_BAIVIET()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_ALL_BAIVIET_Result>("SP_GET_ALL_BAIVIET");
        }
    
        public virtual ObjectResult<SP_GET_ALL_BV_SP_BY_ID_Result> SP_GET_ALL_BV_SP_BY_ID(string mASP)
        {
            var mASPParameter = mASP != null ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_ALL_BV_SP_BY_ID_Result>("SP_GET_ALL_BV_SP_BY_ID", mASPParameter);
        }
    
        public virtual ObjectResult<SP_GET_ALL_DMSP_Result> SP_GET_ALL_DMSP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_ALL_DMSP_Result>("SP_GET_ALL_DMSP");
        }
    
        public virtual ObjectResult<SP_GET_ALL_SANPHAM_Result> SP_GET_ALL_SANPHAM()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_ALL_SANPHAM_Result>("SP_GET_ALL_SANPHAM");
        }
    
        public virtual ObjectResult<SP_GET_ALL_SP_DMSP_BY_ID_Result> SP_GET_ALL_SP_DMSP_BY_ID(string mADMSP)
        {
            var mADMSPParameter = mADMSP != null ?
                new ObjectParameter("MADMSP", mADMSP) :
                new ObjectParameter("MADMSP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_ALL_SP_DMSP_BY_ID_Result>("SP_GET_ALL_SP_DMSP_BY_ID", mADMSPParameter);
        }
    
        public virtual ObjectResult<SP_GET_ALL_VD_SP_BY_ID_Result> SP_GET_ALL_VD_SP_BY_ID(string mASP)
        {
            var mASPParameter = mASP != null ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_ALL_VD_SP_BY_ID_Result>("SP_GET_ALL_VD_SP_BY_ID", mASPParameter);
        }
    
        public virtual ObjectResult<SP_GET_ALL_VIDEO_Result> SP_GET_ALL_VIDEO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_ALL_VIDEO_Result>("SP_GET_ALL_VIDEO");
        }
    
        public virtual ObjectResult<SP_GET_ANH_BY_ID_Result> SP_GET_ANH_BY_ID(string mAANH)
        {
            var mAANHParameter = mAANH != null ?
                new ObjectParameter("MAANH", mAANH) :
                new ObjectParameter("MAANH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_ANH_BY_ID_Result>("SP_GET_ANH_BY_ID", mAANHParameter);
        }
    
        public virtual ObjectResult<SP_GET_BV_BY_ID_Result> SP_GET_BV_BY_ID(string mABV)
        {
            var mABVParameter = mABV != null ?
                new ObjectParameter("MABV", mABV) :
                new ObjectParameter("MABV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_BV_BY_ID_Result>("SP_GET_BV_BY_ID", mABVParameter);
        }
    
        public virtual ObjectResult<SP_GET_DMSP_BY_ID_Result> SP_GET_DMSP_BY_ID(string mADMSP)
        {
            var mADMSPParameter = mADMSP != null ?
                new ObjectParameter("MADMSP", mADMSP) :
                new ObjectParameter("MADMSP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_DMSP_BY_ID_Result>("SP_GET_DMSP_BY_ID", mADMSPParameter);
        }
    
        public virtual ObjectResult<SP_GET_SANPHAM_BY_ID_Result> SP_GET_SANPHAM_BY_ID(string mASP)
        {
            var mASPParameter = mASP != null ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_SANPHAM_BY_ID_Result>("SP_GET_SANPHAM_BY_ID", mASPParameter);
        }
    
        public virtual ObjectResult<SP_GET_VIDEO_BY_ID_Result> SP_GET_VIDEO_BY_ID(string mAVD)
        {
            var mAVDParameter = mAVD != null ?
                new ObjectParameter("MAVD", mAVD) :
                new ObjectParameter("MAVD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_VIDEO_BY_ID_Result>("SP_GET_VIDEO_BY_ID", mAVDParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int SP_SUA_ANH(string mAANH, string mASP, string uRL, byte[] aNHSP, Nullable<bool> iSPENDING, Nullable<bool> iSPUBLISH, Nullable<bool> iSDELETE)
        {
            var mAANHParameter = mAANH != null ?
                new ObjectParameter("MAANH", mAANH) :
                new ObjectParameter("MAANH", typeof(string));
    
            var mASPParameter = mASP != null ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(string));
    
            var uRLParameter = uRL != null ?
                new ObjectParameter("URL", uRL) :
                new ObjectParameter("URL", typeof(string));
    
            var aNHSPParameter = aNHSP != null ?
                new ObjectParameter("ANHSP", aNHSP) :
                new ObjectParameter("ANHSP", typeof(byte[]));
    
            var iSPENDINGParameter = iSPENDING.HasValue ?
                new ObjectParameter("ISPENDING", iSPENDING) :
                new ObjectParameter("ISPENDING", typeof(bool));
    
            var iSPUBLISHParameter = iSPUBLISH.HasValue ?
                new ObjectParameter("ISPUBLISH", iSPUBLISH) :
                new ObjectParameter("ISPUBLISH", typeof(bool));
    
            var iSDELETEParameter = iSDELETE.HasValue ?
                new ObjectParameter("ISDELETE", iSDELETE) :
                new ObjectParameter("ISDELETE", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SUA_ANH", mAANHParameter, mASPParameter, uRLParameter, aNHSPParameter, iSPENDINGParameter, iSPUBLISHParameter, iSDELETEParameter);
        }
    
        public virtual int SP_SUA_BAIVIET(string mABV, string mASP, string tIEUDE, string nOIDUNG, Nullable<bool> iSPENDING, Nullable<bool> iSPUBLISH, Nullable<bool> iSDELETE)
        {
            var mABVParameter = mABV != null ?
                new ObjectParameter("MABV", mABV) :
                new ObjectParameter("MABV", typeof(string));
    
            var mASPParameter = mASP != null ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(string));
    
            var tIEUDEParameter = tIEUDE != null ?
                new ObjectParameter("TIEUDE", tIEUDE) :
                new ObjectParameter("TIEUDE", typeof(string));
    
            var nOIDUNGParameter = nOIDUNG != null ?
                new ObjectParameter("NOIDUNG", nOIDUNG) :
                new ObjectParameter("NOIDUNG", typeof(string));
    
            var iSPENDINGParameter = iSPENDING.HasValue ?
                new ObjectParameter("ISPENDING", iSPENDING) :
                new ObjectParameter("ISPENDING", typeof(bool));
    
            var iSPUBLISHParameter = iSPUBLISH.HasValue ?
                new ObjectParameter("ISPUBLISH", iSPUBLISH) :
                new ObjectParameter("ISPUBLISH", typeof(bool));
    
            var iSDELETEParameter = iSDELETE.HasValue ?
                new ObjectParameter("ISDELETE", iSDELETE) :
                new ObjectParameter("ISDELETE", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SUA_BAIVIET", mABVParameter, mASPParameter, tIEUDEParameter, nOIDUNGParameter, iSPENDINGParameter, iSPUBLISHParameter, iSDELETEParameter);
        }
    
        public virtual int SP_SUA_DANHMUC_SANPHAM(string mADMSP, string tENDMSP, byte[] aNHDMSP, Nullable<bool> iSDELETE)
        {
            var mADMSPParameter = mADMSP != null ?
                new ObjectParameter("MADMSP", mADMSP) :
                new ObjectParameter("MADMSP", typeof(string));
    
            var tENDMSPParameter = tENDMSP != null ?
                new ObjectParameter("TENDMSP", tENDMSP) :
                new ObjectParameter("TENDMSP", typeof(string));
    
            var aNHDMSPParameter = aNHDMSP != null ?
                new ObjectParameter("ANHDMSP", aNHDMSP) :
                new ObjectParameter("ANHDMSP", typeof(byte[]));
    
            var iSDELETEParameter = iSDELETE.HasValue ?
                new ObjectParameter("ISDELETE", iSDELETE) :
                new ObjectParameter("ISDELETE", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SUA_DANHMUC_SANPHAM", mADMSPParameter, tENDMSPParameter, aNHDMSPParameter, iSDELETEParameter);
        }
    
        public virtual int SP_SUA_SANPHAM(string mASP, string mADMSP, string tENSP, Nullable<decimal> gIA, byte[] aNHLONSP, string dONVISP, Nullable<int> sOLUONG, Nullable<int> lUOTVIEW, Nullable<int> lUOTTHICH, string tHONGTIN, string tHONGBAO, Nullable<bool> iSPENDING, Nullable<bool> iSPUBLISH, Nullable<bool> iSDELETE)
        {
            var mASPParameter = mASP != null ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(string));
    
            var mADMSPParameter = mADMSP != null ?
                new ObjectParameter("MADMSP", mADMSP) :
                new ObjectParameter("MADMSP", typeof(string));
    
            var tENSPParameter = tENSP != null ?
                new ObjectParameter("TENSP", tENSP) :
                new ObjectParameter("TENSP", typeof(string));
    
            var gIAParameter = gIA.HasValue ?
                new ObjectParameter("GIA", gIA) :
                new ObjectParameter("GIA", typeof(decimal));
    
            var aNHLONSPParameter = aNHLONSP != null ?
                new ObjectParameter("ANHLONSP", aNHLONSP) :
                new ObjectParameter("ANHLONSP", typeof(byte[]));
    
            var dONVISPParameter = dONVISP != null ?
                new ObjectParameter("DONVISP", dONVISP) :
                new ObjectParameter("DONVISP", typeof(string));
    
            var sOLUONGParameter = sOLUONG.HasValue ?
                new ObjectParameter("SOLUONG", sOLUONG) :
                new ObjectParameter("SOLUONG", typeof(int));
    
            var lUOTVIEWParameter = lUOTVIEW.HasValue ?
                new ObjectParameter("LUOTVIEW", lUOTVIEW) :
                new ObjectParameter("LUOTVIEW", typeof(int));
    
            var lUOTTHICHParameter = lUOTTHICH.HasValue ?
                new ObjectParameter("LUOTTHICH", lUOTTHICH) :
                new ObjectParameter("LUOTTHICH", typeof(int));
    
            var tHONGTINParameter = tHONGTIN != null ?
                new ObjectParameter("THONGTIN", tHONGTIN) :
                new ObjectParameter("THONGTIN", typeof(string));
    
            var tHONGBAOParameter = tHONGBAO != null ?
                new ObjectParameter("THONGBAO", tHONGBAO) :
                new ObjectParameter("THONGBAO", typeof(string));
    
            var iSPENDINGParameter = iSPENDING.HasValue ?
                new ObjectParameter("ISPENDING", iSPENDING) :
                new ObjectParameter("ISPENDING", typeof(bool));
    
            var iSPUBLISHParameter = iSPUBLISH.HasValue ?
                new ObjectParameter("ISPUBLISH", iSPUBLISH) :
                new ObjectParameter("ISPUBLISH", typeof(bool));
    
            var iSDELETEParameter = iSDELETE.HasValue ?
                new ObjectParameter("ISDELETE", iSDELETE) :
                new ObjectParameter("ISDELETE", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SUA_SANPHAM", mASPParameter, mADMSPParameter, tENSPParameter, gIAParameter, aNHLONSPParameter, dONVISPParameter, sOLUONGParameter, lUOTVIEWParameter, lUOTTHICHParameter, tHONGTINParameter, tHONGBAOParameter, iSPENDINGParameter, iSPUBLISHParameter, iSDELETEParameter);
        }
    
        public virtual int SP_SUA_VIDEO(string mAVD, string mASP, string uRL, Nullable<bool> iSPENDING, Nullable<bool> iSPUBLISH, Nullable<bool> iSDELETE)
        {
            var mAVDParameter = mAVD != null ?
                new ObjectParameter("MAVD", mAVD) :
                new ObjectParameter("MAVD", typeof(string));
    
            var mASPParameter = mASP != null ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(string));
    
            var uRLParameter = uRL != null ?
                new ObjectParameter("URL", uRL) :
                new ObjectParameter("URL", typeof(string));
    
            var iSPENDINGParameter = iSPENDING.HasValue ?
                new ObjectParameter("ISPENDING", iSPENDING) :
                new ObjectParameter("ISPENDING", typeof(bool));
    
            var iSPUBLISHParameter = iSPUBLISH.HasValue ?
                new ObjectParameter("ISPUBLISH", iSPUBLISH) :
                new ObjectParameter("ISPUBLISH", typeof(bool));
    
            var iSDELETEParameter = iSDELETE.HasValue ?
                new ObjectParameter("ISDELETE", iSDELETE) :
                new ObjectParameter("ISDELETE", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SUA_VIDEO", mAVDParameter, mASPParameter, uRLParameter, iSPENDINGParameter, iSPUBLISHParameter, iSDELETEParameter);
        }
    
        public virtual int SP_THEM_ANH(string mASP, string uRL, byte[] aNHSP, Nullable<bool> iSPENDING, Nullable<bool> iSPUBLISH, Nullable<bool> iSDELETE)
        {
            var mASPParameter = mASP != null ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(string));
    
            var uRLParameter = uRL != null ?
                new ObjectParameter("URL", uRL) :
                new ObjectParameter("URL", typeof(string));
    
            var aNHSPParameter = aNHSP != null ?
                new ObjectParameter("ANHSP", aNHSP) :
                new ObjectParameter("ANHSP", typeof(byte[]));
    
            var iSPENDINGParameter = iSPENDING.HasValue ?
                new ObjectParameter("ISPENDING", iSPENDING) :
                new ObjectParameter("ISPENDING", typeof(bool));
    
            var iSPUBLISHParameter = iSPUBLISH.HasValue ?
                new ObjectParameter("ISPUBLISH", iSPUBLISH) :
                new ObjectParameter("ISPUBLISH", typeof(bool));
    
            var iSDELETEParameter = iSDELETE.HasValue ?
                new ObjectParameter("ISDELETE", iSDELETE) :
                new ObjectParameter("ISDELETE", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THEM_ANH", mASPParameter, uRLParameter, aNHSPParameter, iSPENDINGParameter, iSPUBLISHParameter, iSDELETEParameter);
        }
    
        public virtual int SP_THEM_BAIVIET(string mASP, string tIEUDE, string nOIDUNG, Nullable<bool> iSPENDING, Nullable<bool> iSPUBLISH, Nullable<bool> iSDELETE)
        {
            var mASPParameter = mASP != null ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(string));
    
            var tIEUDEParameter = tIEUDE != null ?
                new ObjectParameter("TIEUDE", tIEUDE) :
                new ObjectParameter("TIEUDE", typeof(string));
    
            var nOIDUNGParameter = nOIDUNG != null ?
                new ObjectParameter("NOIDUNG", nOIDUNG) :
                new ObjectParameter("NOIDUNG", typeof(string));
    
            var iSPENDINGParameter = iSPENDING.HasValue ?
                new ObjectParameter("ISPENDING", iSPENDING) :
                new ObjectParameter("ISPENDING", typeof(bool));
    
            var iSPUBLISHParameter = iSPUBLISH.HasValue ?
                new ObjectParameter("ISPUBLISH", iSPUBLISH) :
                new ObjectParameter("ISPUBLISH", typeof(bool));
    
            var iSDELETEParameter = iSDELETE.HasValue ?
                new ObjectParameter("ISDELETE", iSDELETE) :
                new ObjectParameter("ISDELETE", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THEM_BAIVIET", mASPParameter, tIEUDEParameter, nOIDUNGParameter, iSPENDINGParameter, iSPUBLISHParameter, iSDELETEParameter);
        }
    
        public virtual int SP_THEM_DANHMUC_SANPHAM(string tENDMSP, byte[] aNHDMSP, Nullable<bool> iSDELETE)
        {
            var tENDMSPParameter = tENDMSP != null ?
                new ObjectParameter("TENDMSP", tENDMSP) :
                new ObjectParameter("TENDMSP", typeof(string));
    
            var aNHDMSPParameter = aNHDMSP != null ?
                new ObjectParameter("ANHDMSP", aNHDMSP) :
                new ObjectParameter("ANHDMSP", typeof(byte[]));
    
            var iSDELETEParameter = iSDELETE.HasValue ?
                new ObjectParameter("ISDELETE", iSDELETE) :
                new ObjectParameter("ISDELETE", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THEM_DANHMUC_SANPHAM", tENDMSPParameter, aNHDMSPParameter, iSDELETEParameter);
        }
    
        public virtual int SP_THEM_SANPHAM(string mADMSP, string tENSP, Nullable<decimal> gIA, byte[] aNHLONSP, string dONVISP, Nullable<int> sOLUONG, Nullable<int> lUOTVIEW, Nullable<int> lUOTTHICH, string tHONGTIN, string tHONGBAO, Nullable<bool> iSPENDING, Nullable<bool> iSPUBLISH, Nullable<bool> iSDELETE)
        {
            var mADMSPParameter = mADMSP != null ?
                new ObjectParameter("MADMSP", mADMSP) :
                new ObjectParameter("MADMSP", typeof(string));
    
            var tENSPParameter = tENSP != null ?
                new ObjectParameter("TENSP", tENSP) :
                new ObjectParameter("TENSP", typeof(string));
    
            var gIAParameter = gIA.HasValue ?
                new ObjectParameter("GIA", gIA) :
                new ObjectParameter("GIA", typeof(decimal));
    
            var aNHLONSPParameter = aNHLONSP != null ?
                new ObjectParameter("ANHLONSP", aNHLONSP) :
                new ObjectParameter("ANHLONSP", typeof(byte[]));
    
            var dONVISPParameter = dONVISP != null ?
                new ObjectParameter("DONVISP", dONVISP) :
                new ObjectParameter("DONVISP", typeof(string));
    
            var sOLUONGParameter = sOLUONG.HasValue ?
                new ObjectParameter("SOLUONG", sOLUONG) :
                new ObjectParameter("SOLUONG", typeof(int));
    
            var lUOTVIEWParameter = lUOTVIEW.HasValue ?
                new ObjectParameter("LUOTVIEW", lUOTVIEW) :
                new ObjectParameter("LUOTVIEW", typeof(int));
    
            var lUOTTHICHParameter = lUOTTHICH.HasValue ?
                new ObjectParameter("LUOTTHICH", lUOTTHICH) :
                new ObjectParameter("LUOTTHICH", typeof(int));
    
            var tHONGTINParameter = tHONGTIN != null ?
                new ObjectParameter("THONGTIN", tHONGTIN) :
                new ObjectParameter("THONGTIN", typeof(string));
    
            var tHONGBAOParameter = tHONGBAO != null ?
                new ObjectParameter("THONGBAO", tHONGBAO) :
                new ObjectParameter("THONGBAO", typeof(string));
    
            var iSPENDINGParameter = iSPENDING.HasValue ?
                new ObjectParameter("ISPENDING", iSPENDING) :
                new ObjectParameter("ISPENDING", typeof(bool));
    
            var iSPUBLISHParameter = iSPUBLISH.HasValue ?
                new ObjectParameter("ISPUBLISH", iSPUBLISH) :
                new ObjectParameter("ISPUBLISH", typeof(bool));
    
            var iSDELETEParameter = iSDELETE.HasValue ?
                new ObjectParameter("ISDELETE", iSDELETE) :
                new ObjectParameter("ISDELETE", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THEM_SANPHAM", mADMSPParameter, tENSPParameter, gIAParameter, aNHLONSPParameter, dONVISPParameter, sOLUONGParameter, lUOTVIEWParameter, lUOTTHICHParameter, tHONGTINParameter, tHONGBAOParameter, iSPENDINGParameter, iSPUBLISHParameter, iSDELETEParameter);
        }
    
        public virtual int SP_THEM_VIDEO(string mASP, string uRL, Nullable<bool> iSPENDING, Nullable<bool> iSPUBLISH, Nullable<bool> iSDELETE)
        {
            var mASPParameter = mASP != null ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(string));
    
            var uRLParameter = uRL != null ?
                new ObjectParameter("URL", uRL) :
                new ObjectParameter("URL", typeof(string));
    
            var iSPENDINGParameter = iSPENDING.HasValue ?
                new ObjectParameter("ISPENDING", iSPENDING) :
                new ObjectParameter("ISPENDING", typeof(bool));
    
            var iSPUBLISHParameter = iSPUBLISH.HasValue ?
                new ObjectParameter("ISPUBLISH", iSPUBLISH) :
                new ObjectParameter("ISPUBLISH", typeof(bool));
    
            var iSDELETEParameter = iSDELETE.HasValue ?
                new ObjectParameter("ISDELETE", iSDELETE) :
                new ObjectParameter("ISDELETE", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THEM_VIDEO", mASPParameter, uRLParameter, iSPENDINGParameter, iSPUBLISHParameter, iSDELETEParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int SP_XOA_ANH(string mAANH)
        {
            var mAANHParameter = mAANH != null ?
                new ObjectParameter("MAANH", mAANH) :
                new ObjectParameter("MAANH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_XOA_ANH", mAANHParameter);
        }
    
        public virtual int SP_XOA_BAIVIET(string mABV)
        {
            var mABVParameter = mABV != null ?
                new ObjectParameter("MABV", mABV) :
                new ObjectParameter("MABV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_XOA_BAIVIET", mABVParameter);
        }
    
        public virtual int SP_XOA_DANHMUC_SANPHAM(string mADMSP)
        {
            var mADMSPParameter = mADMSP != null ?
                new ObjectParameter("MADMSP", mADMSP) :
                new ObjectParameter("MADMSP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_XOA_DANHMUC_SANPHAM", mADMSPParameter);
        }
    
        public virtual int SP_XOA_SANPHAM(string mASP)
        {
            var mASPParameter = mASP != null ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_XOA_SANPHAM", mASPParameter);
        }
    
        public virtual int SP_XOA_VIDEO(string mAVD)
        {
            var mAVDParameter = mAVD != null ?
                new ObjectParameter("MAVD", mAVD) :
                new ObjectParameter("MAVD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_XOA_VIDEO", mAVDParameter);
        }
    
        public virtual ObjectResult<SP_GET_ALL_DMSP_DEMO_Result> SP_GET_ALL_DMSP_DEMO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_ALL_DMSP_DEMO_Result>("SP_GET_ALL_DMSP_DEMO");
        }
    
        public virtual ObjectResult<SP_ALL_LOAIKM_BY_ID_Result> SP_ALL_LOAIKM_BY_ID(Nullable<int> mALOAIKM)
        {
            var mALOAIKMParameter = mALOAIKM.HasValue ?
                new ObjectParameter("MALOAIKM", mALOAIKM) :
                new ObjectParameter("MALOAIKM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ALL_LOAIKM_BY_ID_Result>("SP_ALL_LOAIKM_BY_ID", mALOAIKMParameter);
        }
    
        public virtual ObjectResult<SP_GET_ALL_KHUYENMAI_Result> SP_GET_ALL_KHUYENMAI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_ALL_KHUYENMAI_Result>("SP_GET_ALL_KHUYENMAI");
        }
    
        public virtual ObjectResult<SP_GET_ALL_CHITIETKHUYENMAI_Result> SP_GET_ALL_CHITIETKHUYENMAI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_ALL_CHITIETKHUYENMAI_Result>("SP_GET_ALL_CHITIETKHUYENMAI");
        }
    
        public virtual ObjectResult<SP_GET_CHITIETKHUYENMAI_BY_MASP_MAKM_Result> SP_GET_CHITIETKHUYENMAI_BY_MASP_MAKM(Nullable<int> mALOAIKM, string mASP)
        {
            var mALOAIKMParameter = mALOAIKM.HasValue ?
                new ObjectParameter("MALOAIKM", mALOAIKM) :
                new ObjectParameter("MALOAIKM", typeof(int));
    
            var mASPParameter = mASP != null ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_CHITIETKHUYENMAI_BY_MASP_MAKM_Result>("SP_GET_CHITIETKHUYENMAI_BY_MASP_MAKM", mALOAIKMParameter, mASPParameter);
        }
    
        public virtual ObjectResult<SP_GET_ALL_LOAINHANVIEN_Result> SP_GET_ALL_LOAINHANVIEN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_ALL_LOAINHANVIEN_Result>("SP_GET_ALL_LOAINHANVIEN");
        }
    
        public virtual ObjectResult<SP_GET_LOAINHANVIEN_BY_ID_Result> SP_GET_LOAINHANVIEN_BY_ID(Nullable<int> mALOAINV)
        {
            var mALOAINVParameter = mALOAINV.HasValue ?
                new ObjectParameter("MALOAINV", mALOAINV) :
                new ObjectParameter("MALOAINV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_LOAINHANVIEN_BY_ID_Result>("SP_GET_LOAINHANVIEN_BY_ID", mALOAINVParameter);
        }
    
        public virtual ObjectResult<SP_GET_ALL_NHANVIEN_Result> SP_GET_ALL_NHANVIEN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_ALL_NHANVIEN_Result>("SP_GET_ALL_NHANVIEN");
        }
    
        public virtual ObjectResult<SP_GET_ALL_NHANVIEN_BY_ID_Result> SP_GET_ALL_NHANVIEN_BY_ID(string mANV)
        {
            var mANVParameter = mANV != null ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_ALL_NHANVIEN_BY_ID_Result>("SP_GET_ALL_NHANVIEN_BY_ID", mANVParameter);
        }
    
        public virtual ObjectResult<SP_GET_ALL_CTDH_Result> SP_GET_ALL_CTDH()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_ALL_CTDH_Result>("SP_GET_ALL_CTDH");
        }
    
        public virtual ObjectResult<SP_GET_ALL_DDH_Result> SP_GET_ALL_DDH()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_ALL_DDH_Result>("SP_GET_ALL_DDH");
        }
    
        public virtual ObjectResult<SP_GET_ALL_SANPHAM_DUOC_THICH_Result> SP_GET_ALL_SANPHAM_DUOC_THICH(string mASP)
        {
            var mASPParameter = mASP != null ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_ALL_SANPHAM_DUOC_THICH_Result>("SP_GET_ALL_SANPHAM_DUOC_THICH", mASPParameter);
        }
    
        public virtual ObjectResult<SP_GET_ALL_SP_NHANVIEN_THICH_Result> SP_GET_ALL_SP_NHANVIEN_THICH(string mANV)
        {
            var mANVParameter = mANV != null ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_ALL_SP_NHANVIEN_THICH_Result>("SP_GET_ALL_SP_NHANVIEN_THICH", mANVParameter);
        }
    
        public virtual ObjectResult<SP_GET_ALL_THICHSANPHAM_Result> SP_GET_ALL_THICHSANPHAM()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_ALL_THICHSANPHAM_Result>("SP_GET_ALL_THICHSANPHAM");
        }
    
        public virtual ObjectResult<SP_GET_ALL_BINHLUAN_Result> SP_GET_ALL_BINHLUAN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_ALL_BINHLUAN_Result>("SP_GET_ALL_BINHLUAN");
        }
    
        public virtual ObjectResult<SP_GET_ALL_DANHGIA_Result> SP_GET_ALL_DANHGIA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_ALL_DANHGIA_Result>("SP_GET_ALL_DANHGIA");
        }
    }
}
