//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMIC.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHMUCSANPHAM
    {
        public DANHMUCSANPHAM()
        {
            this.SANPHAMs = new HashSet<SANPHAM>();
        }
    
        public System.Guid MADMSP { get; set; }
        public string TENDMSP { get; set; }
        public byte[] ANHDMSP { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    
        public virtual ICollection<SANPHAM> SANPHAMs { get; set; }
    }
}
