//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMIC.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONDATHANG
    {
        public DONDATHANG()
        {
            this.CHITIETDATHANGs = new HashSet<CHITIETDATHANG>();
        }
    
        public System.Guid MADH { get; set; }
        public Nullable<System.Guid> MANV { get; set; }
        public Nullable<int> TRANGTHAI { get; set; }
        public string DIACHIGIAO { get; set; }
        public Nullable<System.DateTime> NGAYDAT { get; set; }
        public Nullable<System.DateTime> NGAYGIAO { get; set; }
        public string MOTA { get; set; }
    
        public virtual ICollection<CHITIETDATHANG> CHITIETDATHANGs { get; set; }
    }
}
