//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMIC.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAINHANVIEN
    {
        public LOAINHANVIEN()
        {
            this.NHANVIENs = new HashSet<NHANVIEN>();
        }
    
        public int MALOAINV { get; set; }
        public string TENLOAINV { get; set; }
    
        public virtual ICollection<NHANVIEN> NHANVIENs { get; set; }
    }
}
