//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMIC.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAIKHUYENMAI
    {
        public LOAIKHUYENMAI()
        {
            this.CHITIETKHUYENMAIs = new HashSet<CHITIETKHUYENMAI>();
        }
    
        public int MALOAIKM { get; set; }
        public string TENLOAIKM { get; set; }
    
        public virtual ICollection<CHITIETKHUYENMAI> CHITIETKHUYENMAIs { get; set; }
    }
}
