//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMIC.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public NHANVIEN()
        {
            this.BINHLUANs = new HashSet<BINHLUAN>();
            this.DANHGIAs = new HashSet<DANHGIA>();
            this.SANPHAMs = new HashSet<SANPHAM>();
        }
    
        public System.Guid MANV { get; set; }
        public string TENNV { get; set; }
        public string TENDN { get; set; }
        public string MATKHAU { get; set; }
        public string DIACHI { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string SODT { get; set; }
        public string GIOITINH { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> MALOAINV { get; set; }
    
        public virtual ICollection<BINHLUAN> BINHLUANs { get; set; }
        public virtual ICollection<DANHGIA> DANHGIAs { get; set; }
        public virtual LOAINHANVIEN LOAINHANVIEN { get; set; }
        public virtual ICollection<SANPHAM> SANPHAMs { get; set; }
    }
}
